# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

definition_beta <- function(X, Y, Beta, tau, omega_vect, N_iter, computation_norm, thres, non_zeros_pred, lambda_start, ratio_lambda, num_lambda, BIC, verbose) {
    .Call(`_flm_definition_beta`, X, Y, Beta, tau, omega_vect, N_iter, computation_norm, thres, non_zeros_pred, lambda_start, ratio_lambda, num_lambda, BIC, verbose)
}

definition_beta_CV <- function(X_train, Y_train, X_test, Y_test, tau, omega_vect, N_iter, computation_norm, thres, non_zeros_pred, lambda_start, verbose) {
    .Call(`_flm_definition_beta_CV`, X_train, Y_train, X_test, Y_test, tau, omega_vect, N_iter, computation_norm, thres, non_zeros_pred, lambda_start, verbose)
}

